services:
  db:
    image: postgres:16.4-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
      - POSTGRES_DB=backend-sitrack-dev
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
